// <auto-generated />
using System;
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SpotAnalysis.Data.Migrations
{
    [DbContext(typeof(AnalysisContext))]
    [Migration("20260318150137_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Models.Chemical", b =>
                {
                    b.Property<int>("ChemicalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChemicalID"));

                    b.Property<int>("ChemicalTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChemicalID");

                    b.HasIndex("ChemicalTypeID");

                    b.ToTable("Chemicals");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ChemicalType", b =>
                {
                    b.Property<int>("ChemicalTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChemicalTypeID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChemicalTypeID");

                    b.ToTable("ChemicalTypes");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Identity.Group", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Identity.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Identity.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Identity.UserGroup", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "GroupID");

                    b.HasIndex("GroupID");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Identity.UserRole", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Method", b =>
                {
                    b.Property<int>("MethodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MethodID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MethodID");

                    b.ToTable("Methods");
                });

            modelBuilder.Entity("DataAccessLayer.Models.MethodOutput", b =>
                {
                    b.Property<int>("ChemicalID")
                        .HasColumnType("int");

                    b.Property<int>("MethodID")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChemicalID", "MethodID");

                    b.HasIndex("MethodID");

                    b.ToTable("MethodOutputs");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Observation", b =>
                {
                    b.Property<int>("ObservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObservationID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObservationID");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Quizzes.GroupQuiz", b =>
                {
                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<int>("QuizID")
                        .HasColumnType("int");

                    b.HasKey("GroupID", "QuizID");

                    b.HasIndex("QuizID");

                    b.ToTable("GroupQuizzes");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Quizzes.Quiz", b =>
                {
                    b.Property<int>("QuizID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizStatusID")
                        .HasColumnType("int");

                    b.Property<int>("QuizTypeID")
                        .HasColumnType("int");

                    b.HasKey("QuizID");

                    b.HasIndex("QuizStatusID");

                    b.HasIndex("QuizTypeID");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Quizzes.QuizAttempt", b =>
                {
                    b.Property<int>("AttemptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttemptID"));

                    b.Property<DateTime>("Completed")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuizID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Started")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AttemptID");

                    b.HasIndex("QuizID");

                    b.HasIndex("UserID");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Quizzes.QuizStatus", b =>
                {
                    b.Property<int>("QuizStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizStatusID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuizStatusID");

                    b.ToTable("QuizStatus");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Quizzes.QuizType", b =>
                {
                    b.Property<int>("QuizTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizTypeID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuizTypeID");

                    b.ToTable("QuizTypes");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Reaction", b =>
                {
                    b.Property<int>("ReactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReactionID"));

                    b.Property<int>("Chemical1ID")
                        .HasColumnType("int");

                    b.Property<int>("Chemical2ID")
                        .HasColumnType("int");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObservationID")
                        .HasColumnType("int");

                    b.Property<string>("RelevantProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReactionID");

                    b.HasIndex("Chemical1ID");

                    b.HasIndex("Chemical2ID");

                    b.HasIndex("ObservationID");

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTest.STAvailableChemical", b =>
                {
                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int>("ChemicalID")
                        .HasColumnType("int");

                    b.HasKey("QuestionID", "ChemicalID");

                    b.HasIndex("ChemicalID");

                    b.ToTable("STAvailableChemicals");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTest.STAvailableMethod", b =>
                {
                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int>("MethodID")
                        .HasColumnType("int");

                    b.HasKey("QuestionID", "MethodID");

                    b.HasIndex("MethodID");

                    b.ToTable("STAvailableMethods");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTest.STChemicalResult", b =>
                {
                    b.Property<int>("ChemicalResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChemicalResultID"));

                    b.Property<int>("ChosenChemicalID")
                        .HasColumnType("int");

                    b.Property<int>("ResultID")
                        .HasColumnType("int");

                    b.Property<int>("SelectedChemicalID")
                        .HasColumnType("int");

                    b.HasKey("ChemicalResultID");

                    b.HasIndex("ChosenChemicalID");

                    b.HasIndex("ResultID");

                    b.HasIndex("SelectedChemicalID");

                    b.ToTable("STChemicalResults");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTest.STLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<int>("Chemical1ID")
                        .HasColumnType("int");

                    b.Property<int>("Chemical2ID")
                        .HasColumnType("int");

                    b.Property<int>("ResultID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("Chemical1ID");

                    b.HasIndex("Chemical2ID");

                    b.HasIndex("ResultID");

                    b.ToTable("STLogs");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTest.STQuestion", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<int?>("ChemicalID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizID")
                        .HasColumnType("int");

                    b.HasKey("QuestionID");

                    b.HasIndex("ChemicalID");

                    b.HasIndex("QuizID");

                    b.ToTable("STQuestion");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTest.STResult", b =>
                {
                    b.Property<int>("ResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultID"));

                    b.Property<int>("AttemptID")
                        .HasColumnType("int");

                    b.Property<int?>("ChemicalID")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.HasKey("ResultID");

                    b.HasIndex("AttemptID");

                    b.HasIndex("ChemicalID");

                    b.HasIndex("QuestionID");

                    b.ToTable("STResults");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTestLight.STLAvailableReaction", b =>
                {
                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int>("ReactionID")
                        .HasColumnType("int");

                    b.HasKey("QuestionID", "ReactionID");

                    b.HasIndex("ReactionID");

                    b.ToTable("STLAvailableReactions");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTestLight.STLQuestion", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<int>("ChemicalID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObservationID")
                        .HasColumnType("int");

                    b.Property<int>("QuizID")
                        .HasColumnType("int");

                    b.HasKey("QuestionID");

                    b.HasIndex("ChemicalID");

                    b.HasIndex("ObservationID");

                    b.HasIndex("QuizID");

                    b.ToTable("STLQuestions");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTestLight.STLResult", b =>
                {
                    b.Property<int>("ResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultID"));

                    b.Property<int>("AttemptID")
                        .HasColumnType("int");

                    b.Property<int>("ChosenChemicalID")
                        .HasColumnType("int");

                    b.Property<int>("ChosenReactionID")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.HasKey("ResultID");

                    b.HasIndex("AttemptID");

                    b.HasIndex("ChosenChemicalID");

                    b.HasIndex("ChosenReactionID");

                    b.HasIndex("QuestionID");

                    b.ToTable("STLResults");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Chemical", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ChemicalType", "ChemicalType")
                        .WithMany("Chemicals")
                        .HasForeignKey("ChemicalTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChemicalType");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Identity.UserGroup", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Identity.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Identity.UserRole", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Models.MethodOutput", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Chemical", "Chemical")
                        .WithMany("MehtodOutputs")
                        .HasForeignKey("ChemicalID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Method", "Method")
                        .WithMany("MethodOutputs")
                        .HasForeignKey("MethodID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chemical");

                    b.Navigation("Method");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Quizzes.GroupQuiz", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Identity.Group", "Group")
                        .WithMany("GroupQuizzes")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Quizzes.Quiz", "Quiz")
                        .WithMany("GroupQuizzes")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Quizzes.Quiz", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Quizzes.QuizStatus", "QuizStatus")
                        .WithMany("Quizzes")
                        .HasForeignKey("QuizStatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Quizzes.QuizType", "QuizType")
                        .WithMany("Quizzes")
                        .HasForeignKey("QuizTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuizStatus");

                    b.Navigation("QuizType");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Quizzes.QuizAttempt", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Quizzes.Quiz", "Quiz")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Reaction", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Chemical", "Chemical1")
                        .WithMany("Chemical1Reactions")
                        .HasForeignKey("Chemical1ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Chemical", "Chemical2")
                        .WithMany("Chemical2Reactions")
                        .HasForeignKey("Chemical2ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Observation", "Observation")
                        .WithMany("Reactions")
                        .HasForeignKey("ObservationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chemical1");

                    b.Navigation("Chemical2");

                    b.Navigation("Observation");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTest.STAvailableChemical", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Chemical", "Chemical")
                        .WithMany("STAvailableChemicals")
                        .HasForeignKey("ChemicalID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.SpotTest.STQuestion", "Question")
                        .WithMany("AvailableChemicals")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chemical");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTest.STAvailableMethod", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Method", "Method")
                        .WithMany("STAvailableMethods")
                        .HasForeignKey("MethodID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.SpotTest.STQuestion", "Question")
                        .WithMany("AvailableMethods")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Method");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTest.STChemicalResult", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Chemical", "ChosenChemical")
                        .WithMany()
                        .HasForeignKey("ChosenChemicalID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.SpotTest.STResult", "Result")
                        .WithMany("ChemicalResults")
                        .HasForeignKey("ResultID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Chemical", "SelectedChemical")
                        .WithMany()
                        .HasForeignKey("SelectedChemicalID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChosenChemical");

                    b.Navigation("Result");

                    b.Navigation("SelectedChemical");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTest.STLog", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Chemical", "Chemical1")
                        .WithMany()
                        .HasForeignKey("Chemical1ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Chemical", "Chemical2")
                        .WithMany()
                        .HasForeignKey("Chemical2ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.SpotTest.STResult", "Result")
                        .WithMany("STLogs")
                        .HasForeignKey("ResultID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chemical1");

                    b.Navigation("Chemical2");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTest.STQuestion", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Chemical", null)
                        .WithMany("STQuestions")
                        .HasForeignKey("ChemicalID");

                    b.HasOne("DataAccessLayer.Models.Quizzes.Quiz", "Quiz")
                        .WithMany("STQuestions")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTest.STResult", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Quizzes.QuizAttempt", "Attempt")
                        .WithMany("STResults")
                        .HasForeignKey("AttemptID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Chemical", null)
                        .WithMany("STResults")
                        .HasForeignKey("ChemicalID");

                    b.HasOne("DataAccessLayer.Models.SpotTest.STQuestion", "Question")
                        .WithMany("Results")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTestLight.STLAvailableReaction", b =>
                {
                    b.HasOne("DataAccessLayer.Models.SpotTestLight.STLQuestion", "STLQuestion")
                        .WithMany("AvailableReactions")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Reaction", "Reaction")
                        .WithMany("STLAvailableReactions")
                        .HasForeignKey("ReactionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reaction");

                    b.Navigation("STLQuestion");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTestLight.STLQuestion", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Chemical", "Chemical")
                        .WithMany("STLQuestions")
                        .HasForeignKey("ChemicalID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Observation", "Observation")
                        .WithMany("STLQuestions")
                        .HasForeignKey("ObservationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Quizzes.Quiz", "Quiz")
                        .WithMany("STLQuestions")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chemical");

                    b.Navigation("Observation");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTestLight.STLResult", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Quizzes.QuizAttempt", "Attempt")
                        .WithMany("STLResults")
                        .HasForeignKey("AttemptID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Chemical", "ChosenChemical")
                        .WithMany("STLResults")
                        .HasForeignKey("ChosenChemicalID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Reaction", "ChosenReaction")
                        .WithMany("STLResults")
                        .HasForeignKey("ChosenReactionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.SpotTestLight.STLQuestion", "Question")
                        .WithMany("STLResults")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("ChosenChemical");

                    b.Navigation("ChosenReaction");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Chemical", b =>
                {
                    b.Navigation("Chemical1Reactions");

                    b.Navigation("Chemical2Reactions");

                    b.Navigation("MehtodOutputs");

                    b.Navigation("STAvailableChemicals");

                    b.Navigation("STLQuestions");

                    b.Navigation("STLResults");

                    b.Navigation("STQuestions");

                    b.Navigation("STResults");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ChemicalType", b =>
                {
                    b.Navigation("Chemicals");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Identity.Group", b =>
                {
                    b.Navigation("GroupQuizzes");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Identity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Identity.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Method", b =>
                {
                    b.Navigation("MethodOutputs");

                    b.Navigation("STAvailableMethods");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Observation", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("STLQuestions");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Quizzes.Quiz", b =>
                {
                    b.Navigation("GroupQuizzes");

                    b.Navigation("QuizAttempts");

                    b.Navigation("STLQuestions");

                    b.Navigation("STQuestions");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Quizzes.QuizAttempt", b =>
                {
                    b.Navigation("STLResults");

                    b.Navigation("STResults");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Quizzes.QuizStatus", b =>
                {
                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Quizzes.QuizType", b =>
                {
                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Reaction", b =>
                {
                    b.Navigation("STLAvailableReactions");

                    b.Navigation("STLResults");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTest.STQuestion", b =>
                {
                    b.Navigation("AvailableChemicals");

                    b.Navigation("AvailableMethods");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTest.STResult", b =>
                {
                    b.Navigation("ChemicalResults");

                    b.Navigation("STLogs");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SpotTestLight.STLQuestion", b =>
                {
                    b.Navigation("AvailableReactions");

                    b.Navigation("STLResults");
                });
#pragma warning restore 612, 618
        }
    }
}
